#!/usr/bin/env python3

import sys
import shutil
from os                 import (path, environ)
from lib.testlists      import *

repo_dir = path.dirname(__file__)
sys.path.append(path.join(repo_dir, 'ext/'))
from kninja import *
environ['PATH'] = path.join(repo_dir, 'ext/k-light/bin/') + ':' + environ['PATH']

# Project Definition
# ==================

proj = KProject()

# Matching Logic Prover
# =====================

other_md_files = [ 'lang/smt-lang.md'
                 , 'lang/kore-lang.md'
                 , 'drivers/base.md'
                 , 'drivers/smt-driver.md'
                 , 'drivers/kore-driver.md'
                 , 'strategies/apply.md'
                 , 'strategies/apply-equation.md'
                 , 'strategies/core.md'
                 , 'strategies/duplicate.md'
                 , 'strategies/instantiate-universals.md'
                 , 'strategies/inst-exists.md'
                 , 'strategies/intros.md'
                 , 'strategies/knaster-tarski.md'
                 , 'strategies/matching.md'
                 , 'strategies/reflexivity.md'
                 , 'strategies/replace-evar-with-func-constant.md'
                 , 'strategies/simplification.md'
                 , 'strategies/search-bound.md'
                 , 'strategies/smt.md'
                 , 'strategies/unfolding.md'
                 , 'utils/error.md'
                 , 'utils/instantiate-assumptions.md'
                 , 'utils/load-named.md'
                 , 'utils/heatcool.md'
                 , 'utils/syntactic-match.md'
                 , 'utils/visitor.md'
                 ]

def prover(alias, flags = None):
    return proj.definition( alias = alias
                          , backend = 'ocaml'
                          , main = 'prover.md'
                          , other = other_md_files
                          , runner_script = './prover'
                          , flags = flags
                          )

prover_kore = prover('prover-kore', '--main-module DRIVER-KORE --syntax-module DRIVER-KORE-SYNTAX')
prover_smt  = prover('prover-smt',  '--main-module DRIVER-SMT  --syntax-module DRIVER-SMT-SYNTAX' )

# Functional tests
# ----------------

prover_kore.tests(inputs = glob('t/**/*.kore'), implicit_inputs = glob('t/definitions/*.kore'), flags = '-cCOMMANDLINE=.CommandLine')
prover_smt .tests(inputs = glob('t/sl/*.smt2'), flags = '-cCOMMANDLINE=.CommandLine')

def log_on_success(file, message):
    return proj.rule( 'log-to-success'
                    , description = '$out: $message'
                    , command = "echo '$message' >> '$log_file'"
                    ) \
               .variable('log_file', file) \
               .variable('message',  message) \
               .ext(file.replace('/', '.'))

def krun_with_timeout(timeout_flags):
    # TODO: This timeout functionality should become a part of the runner script
    # or KNinja
    timeout_cmd = 'gtimeout' if shutil.which("gtimeout") else 'timeout'
    return prover_smt.krun() \
                     .ext('timeout') \
                     .variable('env', timeout_cmd + ' ' + timeout_flags + ' opam config exec --') \

def config_for_test(test):
    for list_config in test_lists:
        prefix, ktbound, unfold_bound, timeout, list = list_config
        passing = True
        if test in list: return (prefix, ktbound, unfold_bound, timeout, passing)
    return ("unfold-mut-recs . ", 5, 12, '20m', False)
def strategy_for_test(test):
    (prefix, ktbound, unfold_bound, timeout, passing) = config_for_test(test)
    strategy = prefix + 'search-sl(kt-bound: %d, unfold-bound: %d)' % (ktbound, unfold_bound)
    return strategy
def timeout_for_test(test):
    (prefix, ktbound, unfold_bound, timeout, passing) = config_for_test(test)
    return timeout
def known_passing(test):
    (prefix, ktbound, unfold_bound, timeout, passing) = config_for_test(test)
    return passing

def make_test(rule, test):
    commandline = "'--default-strategy %s'" % strategy_for_test(test)
    return proj.source(test) \
               .then(rule.variable('flags', '-cCOMMANDLINE=%s' % commandline))

def sl_comp_test(test, log_file):
    global tests_with_timeout
    test_no_timeout   = make_test(prover_smt.krun().ext('prover-smt-run'), test)
    test_with_timeout = make_test(krun_with_timeout(timeout_for_test(test)), test) \
                          .then(log_on_success(log_file, test))
    return (test_no_timeout, test_with_timeout)

known_passing_tests = []
remaining_tests     = []
separation_logic_tests_all = []
for t in qf_shid_entl_unsat_tests:
    (test_no_timeout, test_with_timeout) = sl_comp_test(t, '.build/passed')
    if known_passing(t):
        known_passing_tests += [test_with_timeout]
        separation_logic_tests_all += [test_no_timeout.path]
    else:                remaining_tests     += [test_with_timeout]
proj.alias('known-passing',   known_passing_tests).default()
proj.alias('remaining-tests', remaining_tests)

def secondary_tests(alias, file):
    list = read_list(file)
    tests = []
    for t in list:
        (test_no_timeout , test_with_timeout) = sl_comp_test(t, '.build/%s.passed' % alias)
        tests += [test_with_timeout]
    proj.alias(alias, tests)
secondary_tests('qf_shidlia_entl_unsat_tests', 't/test-lists/qf_shidlia_entl.unsat')
secondary_tests('qf_shlid_entl_unsat_tests',   't/test-lists/qf_shlid_entl.unsat')
secondary_tests('shid_entl_unsat_tests',       't/test-lists/shid_entl.unsat')

# TODO: Why are smt tests `-krun` and kore tests `-run`?
def test_path(name, type):
    return ".build/t/%s.%s" % (name, type)
def sl_comp_test_path(name):
    return test_path("sl/SL-COMP18/bench/qf_shid_entl/%s" % name, 'prover-smt-run')

separation_logic_2 = [ '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll-entails-dll-rev.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll-rev-entails-dll-mid.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll-rev-entails-dll.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll_append_tail_entails_dllnull_nil.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll_concat_dllrev.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll_entails_dllrev.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll_entails_lspre.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll_entails_lsrev.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dll_nil_tl_entails_dllnull.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dllrev_append_head_entails_dll.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/dllrev_entails_dll.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/eolseg_01.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/eolseg_05.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/eolseg_06.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/eolseg_07.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/eolseg_12.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/eolseg_15.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_entail_ls_nonrec_16.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_even_join_entails_ls.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_even_join_ls_entails_ls.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_lsrev_concat_entail_ls_2.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_lsrev_concat_entail_lsrev_2.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_nonrec_entail_ls_13.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_nonrec_entail_ls_14.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/ls_odd_join_entails_ls.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsevenodd_14.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsevenodd_15.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsevenodd_ls2_09.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsevenodd_ls2_15.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsevenodd_ls2_16.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsleftright_07.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsleftright_10.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsleftright_11.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsleftright_12.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsleftright_13.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsleftright_19.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/lsleftright_20.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/nll-vc07.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/nll-vc09.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/node-dll-rev-dll-entails-dll.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/tseg_join_2_entail_tree.sb.smt2.prover-smt-run'
                     , '.build/t/sl/SL-COMP18/bench/qf_shid_entl/tseg_join_tree.sb.smt2.prover-smt-run'
                     ]
separation_logic_tests = list(set(separation_logic_tests_all) - set(separation_logic_2))
separation_logic_tests = list(set(separation_logic_tests_all) - set(separation_logic_2))
proj.alias('separation-logic-tests',  separation_logic_tests)
print(len(separation_logic_tests_all))
print(len(separation_logic_tests))

proj.alias('smoke-tests', list(map( sl_comp_test_path, [ 
           "02.tst.smt2"                         , # RList trans 
           "10.tst.smt2"                         , # ListO * ListO -> ListE 
           "16.tst.smt2"                         , # BinPath -> BinTreeSeg, needs no unfold of define-fun-recs 
           "append_sll_cll_slk-7.smt2"           , # need left-unfold at start 
           "22.tst.smt2"                         , # needs multiple left-unfolds within kts 
           "dll-mid-entails-dll-rev.smt2"        , # needs abstract
           "tll_slk-13.smt2"                     , # alternate-search-bound due to large number of rec defs, not using right-unfold-all 
           "skl2-vc03.smt2"                      , # needs framing but not match-pto 
           "odd-lseg3_slk-5.smt2"                , # needs framing and match-pto 
           "nll-vc01.smt2"                       , # needs large number of unfolding but no kt
           "ls_nonrec_entail_ls_05.sb.smt2"      , # 4 variable transitivity: ls_nonrec(x,x1) * ... * ls_nonrec(x4,x5) -> ls(x,x5)  - needs large number of kts and unfolding
           "ls_lsrev_concat_entail_ls_1.sb.smt2" , # need unfolding within implication context
           "dll-vc05.smt2"                       , # requires footprint analysis
          ])) +
          [ test_path('fol/avl-implies-bst.kore', 'prover-kore-run')
          ]
          )

# Unit Tests
# ----------

unit_tests_sources = glob('t/unit/*.k')
test_driver = proj.definition( alias = 'test-driver'
                             , backend = 'ocaml'
                             , main = 'drivers/unit-tests.md'
                             , other = other_md_files + ['prover.md'] + unit_tests_sources
                             , runner_script = './prover'
                             , flags = '-I . --main-module DRIVER-UNIT-TEST' # -ccopt -O0'
                             )
proj.alias('unit-tests'
          , [ proj.source('t/unit/unit-tests')
                  .then(test_driver.krun()
                                   .variable('flags', '-cCOMMANDLINE=.CommandLine')
                       )
            ]
          ).default()

if __name__ == "__main__": proj.main()
