load checker .

fmod TEST is including CHECKER .

op proof-1 : -> Proof .
eq proof-1 =
(1) (\evar 1) (WF) ;
(2) (\imp (1) (1)) (WF) ; 
(3) (\imp (1) (2)) (WF) ;
(4) (\imp (2) (1)) (WF) ;
(5) (\imp (1) (4)) (WF) ;
(6) (\imp (3) (2)) (WF) ;
(7) (\imp (5) (6)) (WF) ; 
(8) (5) (PropK (1) (2)) ;
(9) (7) (PropS (1) (2) (1)) ;
(10) (6) (MP (8) (9)) ;
(11) (3) (PropK (1) (1)) ;
(12) (2) (MP (11) (10)) ;
.

op proof-3 : -> Proof .
eq proof-3 =
(1) (\evar 1) (WF) ;
(2) (\evar 2) (WF) ;
(3) (\ex (1) (1)) (WF) ; " \ex x1 . x1 "
(4) (\imp (1) (3)) (WF) ; " x1 -> \ex x1 . x1 "
(5) (4) (ExistQ (3) (1)) ;
(6) (\imp (2) (3)) (WF) ; " x2 -> \ex x1 . x1 "
(7) (6) (ExistQ (3) (2)) ;
.

endfm

reduce check(proof-1) .
---- reduce check(proof-3) .

quit
