#!/usr/bin/env bash

# Usage: $0 tests/testname.clpr

base_dir=$(cd $(dirname $0); pwd)

export PATH=$base_dir:$base_dir/z3/bin:$PATH
export LD_LIBRARY_PATH=$base_dir/z3/lib:$LD_LIBRARY_PATH
export CLPRLIB=$base_dir
export CLPR_BASE_PATH=$base_dir

exec clpr "$@"
