#!/bin/sh
prover_dir=$(cd $(dirname $0); pwd -P)

if [ $# -ne 1 ]; then
  echo "Usage: $0 file.kore"
  exit 1
fi

file="$1"

"$prover_dir/prover" run --definition prover-kore "$file" -cCOMMANDLINE=.CommandLine -cPROVERDIR="\"$prover_dir\""
