#!/usr/bin/env python3
extdir = 'ext'
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), extdir))
from kninja.runner import *

proj = KProject(extdir = extdir)
KDefinition( proj
           , alias = 'prover'
           , backend = 'ocaml'
           , directory = proj.builddir('defn/prover')
           , krun_flags = '--interpret'
           )
KDefinition( proj
           , alias = 'test-matching'
           , backend = 'ocaml'
           , directory = proj.builddir('defn/test-matching')
           , krun_flags = '--interpret'
           )
KDefinition( proj
           , alias = 'smtlib'
           , backend = 'java'
           , directory = proj.builddir('defn/smtlib')
           )
KRunner(proj).main()
