--- Pattern ---
parse \not a .
parse \not \bottom .
parse \not \top .
parse < a > a .
parse < a > X .
parse [ a ] a .
parse [ a ] X .
parse \and(X, \and(Y, Z))  .
parse \and(\and(Y, Z), Z)  .
reduce \and(\and(Y, Z), Z)  .

--- SetVariable ---
reduce X in (X,Y) .
reduce X in (Y,Y) .

--- Free Variables ---
reduce fv(\and(X, Y)) .
reduce fv(\or(X, Y)) .
reduce fv(\nu X . X) .
reduce fv(\nu X . Y) .
reduce fv(\nu X . \and(X, Y)) .
reduce fv(\mu X . X) .
reduce fv(\mu X . Y) .
reduce fv(\mu X . \and(X, Y)) .
