set show timing off .

--- Pattern ---
---------------

select MATCHING-LOGIC-PATTERN .

parse \not a .
parse < a > a .
parse < a > X .
parse [ a ] a .
parse [ a ] X .
parse \and(X, \and(Y, Z))  .
parse \and(\and(Y, Z), Z)  .
reduce \and(\and(Y, Z), Z)  .

--- Not allowed
parse \not \bottom .
parse \not \top .

--- SetVariableSet ---
----------------------

select MATCHING-LOGIC-SUBSTITUTION .

reduce X in (X,Y) .
reduce X in (Y,Y) .

--- Free Variables ---
----------------------

select MATCHING-LOGIC-SUBSTITUTION .

reduce fv(\and(X, Y)) .
reduce fv(\or(X, Y)) .
reduce fv(\nu X . X) .
reduce fv(\nu X . Y) .
reduce fv(\nu X . \and(X, Y)) .
reduce fv(\mu X . X) .
reduce fv(\mu X . Y) .
reduce fv(\mu X . \and(X, Y)) .

--- Substitution ---
--------------------

select MATCHING-LOGIC-SUBSTITUTION .

reduce [X := Y] a .

reduce [X := Y] Z .
reduce [X := Y] X .

reduce [X := Y] < a > X .
reduce [X := Y] < a > Y .
reduce [X := Y] < a > Z .
reduce [X := Y] [ a ] X .
reduce [X := Y] [ a ] Y .
reduce [X := Y] [ a ] Z .

reduce [X := Y] \and(X, Y) .
reduce [X := Y] \and(Y, X) .
reduce [X := Y] \and(Z, Y) .
reduce [X := Y] \or (X, Y) .
reduce [X := Y] \or (Y, X) .
reduce [X := Y] \or (Z, Y) .

reduce [X := Y] \mu X . X .
reduce [X := Y] \mu X . Y .
reduce [X := Y] \mu Z . X .
reduce [X := Y] \mu Z . Y .
reduce [X := Y] \mu Z . Z .

reduce [X := Y] \nu X . X .
reduce [X := Y] \nu X . Y .
reduce [X := Y] \nu Z . X .
reduce [X := Y] \nu Z . Y .
reduce [X := Y] \nu Z . Z .

--- These aren't handled yet, but should be once we have full ML support
parse  [X := Y] < X > a .
parse  [X := Y] [ X ] a .


--- Tableaux ---
----------------

select MATCHING-LOGIC-TABLEAUX .

reduce contract(X) .
reduce contract(a) .
reduce contract(\and(X, Y)) .

reduce contract(\and( \mu X . \or(b, < a > X)
                    , \mu Y . \or(b, < a > Y)
                    )
               ) .
reduce contract(\and( \mu X . \or(b, < a > X)
                    , \mu Y . \or(b, < c > Y)
                    )
               ) .
reduce contract(\and( \mu X . \or(b, < a > X)
                    , \mu X . \or(b, < a > X)
                    )
               ) .

reduce contract( \and( \mu X . \or ([ a ] X, \nu Y . \and([ a ] Y, c))
                     , \nu X . \and(< a > X, \mu Y . \or (< a > Y, \not c))
               )     ) .


--- isConsistent 

reduce isConsistent(\and(\mu X . \or([a]X, \nu Y . \and(c, [a]Y)), \nu X . \and(< a > X, \mu Y . \or(\not c, < a > Y)))) .
reduce isConsistent(c, a, \not c) .
reduce isConsistent(c, a) .
reduce isConsistent(\not c, a) .
