#!/bin/bash

language="twocounters"
language_definition=$language.k
program="100".$language

function generate_snapshots() {
    step=0
    maxstep=100
    mkdir -p snapshots
    while [ "$step" -le "100" ]; do
        echo "generating snapshot_$step.kore"
        krun $program --depth $step --output kore >> snapshots/snapshot_$step.kore
        step=$(($step + 1))
    done
}

function convert_snapshots() {

}

#### Main Entry

arg1=$1

if [ "$arg1" = "snapshots" ]; 
then
    echo "generating snapshots..."
    generate_snapshots
else if [ "$arg1" = "convert" ];
then
    echo "converting snapshots..."
    convert_snapshots
else if [ "$arg1" = "clear" ];
then 
    rm -rf snapshots/
else 
    echo "unknown options."
fi fi
