#!/bin/bash

printf "lexing \"lexer.mll\" ...\n"
ocamllex lexer.mll

printf "\nyaccing \"parser.mly\"...\n"
ocamlyacc parser.mly

printf "\ncompiling \"convert.ml\" ...\n"
ocamlc -c convert.ml

printf "\ncompiling \"parser.mli\" ...\n"
ocamlc -c parser.mli

printf "\ncompiling \"lexer.ml\" ...\n"
ocamlc -c lexer.ml

printf "\ncompiling \"parser.ml\" ...\n"
ocamlc -c parser.ml

printf "\ncompiling \"main.ml\" ...\n"
ocamlc -c main.ml

printf "\nmaking final binaries ...\n"
ocamlc -o ml2fol lexer.cmo convert.cmo parser.cmo main.cmo

printf "\ncreating tests ...\n"
ocamlfind ocamlc -o test -package oUnit -linkpkg -g convert.ml test.ml

printf "\nrunning test suites ...\n"
./test

printf "\ncleaning ...\n"
rm *.cmo *.cmi parser.mli lexer.ml parser.ml *.cache *.log test
