#!/usr/bin/bash
ocamllex lexer.mll
ocamlyacc parser.mly
ocamlc -c parser.mli
ocamlc -c lexer.ml
ocamlc -c parser.ml
ocamlc -c convert.ml
ocamlc -c main.ml
ocamlc -o main lexer.cmo convert.cmo parser.cmo main.cmo
#rm parser.mli lexer.ml parser.ml
